sudo: required
language: node_js
notifications:
  email: luizeduardo354@gmail.com
node_js:
- 12.14.0
services:
- mysql
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
addons:
  mysql: '5.5.56'
before_script:
  - mysql -u root < tests/db/estudo_test.sql
  - mysql -u root -e "CREATE USER 'tester'@'localhost' IDENTIFIED BY 'local@test';";
  - mysql -u root -e "GRANT ALL PRIVILEGES ON estudo_test.* TO 'tester'@'localhost';";
  - npm i -g gulp-cli
  - npm install
  - gulp
script:
- npm run u-test
- npm run i-test