dist: trusty
language: node_js
notifications:
  email: luizeduardo354@gmail.com
node_js:
- 12.14.0
services:
- mysql
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
addons:
  sonarcloud:
    organization: "luiscomp"
    token:
      secure: "e9f44b1380601a9df3d3281381a7c27aabc3000d"
before_script:
  - mysql -u root < tests/db/Schema.sql
  - mysql -u root -e 'USE amigo;'
  - mysql source tests/db/Empresa.sql
  - mysql source tests/db/Usuario.sql
  - mysql -u root -e "CREATE USER 'tester'@'localhost' IDENTIFIED BY 'local@test';";
  - mysql -u root -e "GRANT ALL PRIVILEGES ON amigo.* TO 'tester'@'localhost';";
  - npm i -g gulp-cli
  - npm install
  - gulp
script: echo "Executanto tarefa..."
jobs:
  include:
    - stage: "Testes"
      script: 
        - npm run u-test
        - npm run i-test
    - stage: "Sonar Scanner"
      script: sonar-scanner
    