dist: trusty
language: node_js
notifications:
  email: luizeduardo354@gmail.com
node_js:
- 12.14.0
services:
- mysql
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
addons:
  sonarcloud:
    organization: "luiscomp"
    token: "54c359dc7f030fb6a68f43fd0c1724ed6168a227"
    projectKey: "luiscomp_node-backend"
    branches:
    - master
before_script:
  - mysql -u root < tests/db/Schema.sql
  - mysql -u root amigo < tests/db/Empresa.sql
  - mysql -u root amigo < tests/db/Usuario.sql
  - mysql -u root -e "SHOW databases;"
  - mysql -u root -e "CREATE USER 'tester'@'localhost' IDENTIFIED BY 'local@test';";
  - mysql -u root -e "GRANT ALL PRIVILEGES ON amigo.* TO 'tester'@'localhost';";
  - npm i -g gulp-cli
  - npm install
  - gulp
  - ls -l
script: echo "Executanto tarefa..."
jobs:
  include:
    - stage: "Testes e Coverage"
      script: 
        - npm run u-cover
        - npm run i-cover
        - sonar-scanner
    